title: Llenguatges de Marues i Sistemes de Gestió de la informació
description: Curs 2024-2025 IES Benigasló
theme: just-the-docs

url: https://jaume-av.github.io/LLMM

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
