title: Llenguatges de Marques - IES Benigasló
description: Llenguatges de Marques i Sistemes de Gestió de la Informació.
theme: just-the-docs

url: https://jaume-av.github.io/LLMM/
baseurl: "/LLMM" 

aux_links:
  "Accés a Aules":
    - https://aules.edu.gva.es/fp/

search_enabled: true


# Navegació directa sense desplegables
collections:
  docs:
    output: true
    permalink: /:path/